import { createSlice } from "@reduxjs/toolkit";

const faAccountsSlice = createSlice({
  name: "faAccounts",
  initialState: [
    {
      id: 15,
      title: "mystery box",
      desc: "",
      img: "https://i.postimg.cc/RhZcGckP/1.png",
      value: "€",
      price: "10",
    },
    {
      id: 16,
      title: "1+ Skin",
      desc: "",
      img: "https://i.postimg.cc/d3V8n8bp/2.png",

      value: "€",
      price: "3",
    },
    {
      id: 17,
      title: "10+ Skin",
      desc: "",
      img: "https://i.postimg.cc/1X3pMGx1/3.png",
      value: "€",
      price: "5",
    },
    {
      id: 18,
      title: "Leviathan Axe",
      desc: "",
      img: "https://i.postimg.cc/3Nxg9XMM/4.png",
      value: "€",
      price: "20",
    },
    {
      id: 19,
      title: "Minty Axe",
      desc: "",
      img: "https://i.postimg.cc/rswSgSB7/5.png",
      value: "€",
      price: "20",
    },
    {
      id: 20,
      title: "Mako",
      desc: "",
      img: "https://i.postimg.cc/FzHjGyt4/6.png",
      value: "€",
      price: "20",
    },
    {
      id: 21,
      title: "Glow",
      desc: "",
      img: "https://i.postimg.cc/7hZgX3vw/7.png",
      value: "€",
      price: "20",
    },
    {
      id: 22,
      title: "Season 2",
      desc: "",
      img: "https://i.postimg.cc/1X7Dd8ST/8.png",
      value: "€",
      price: "25",
    },
    {
      id: 23,
      title: "Season 3",
      desc: "",
      img: "https://i.postimg.cc/5y2wpBcf/9.png",
      value: "€",
      price: "25",
    },
    {
      id: 24,
      title: "Season 4",
      desc: "",
      img: "https://i.postimg.cc/mkp7nP4K/10.png",
      value: "€",
      price: "20",
    },
    {
      id: 25,
      title: "Travis Scott",
      desc: "",
      img: "https://i.postimg.cc/kGYWH2Ck/11.png",
      value: "€",
      price: "50",
    },
    {
      id: 26,
      title: "Ikonik or Galaxy",
      desc: "",
      img: "https://i.postimg.cc/MH31Lnxk/12.png",
      value: "€",
      price: "50",
    },
    {
      id: 27,
      title: "Personalizzato",
      desc: "",
      img: "https://i.postimg.cc/tJvFcsyH/13.png",
      value: "",
      price: "su richiesta",
    },
    {
      id: 28,
      title: "Black Knight",
      desc: "",
      img: "https://i.postimg.cc/90gykDVh/14.png",
      value: "€",
      price: "100",
    },
    {
      id: 29,
      title: "OG Skin",
      desc: "",
      img: "https://i.postimg.cc/7htSR5DD/15.png",
      value: "",
      price: "su richiesta",
    },
  ],
});

export default faAccountsSlice.reducer;
